ALTER TABLE rooms ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES rooms(id) ON DELETE CASCADE;
ALTER TABLE room_members ADD COLUMN IF NOT EXISTS active_sub_room_id UUID REFERENCES rooms(id) ON DELETE SET NULL;
